name: tests
on:
  push:
    branches: ['main']
    paths-ignore:
      - "docs/*"
  pull_request:
    paths-ignore:
      - "docs/*"
permissions: read-all
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: ['1.22', '1.23']
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871
    - name: Install Go
      uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32
      with:
        go-version: ${{ matrix.go-version }}
        cache: true
    - name: Test
      run: go test -timeout 20m ./...
