name: tests
on:
  push:
    branches: ['main']
    paths-ignore:
      - "docs/*"
  pull_request:
    paths-ignore:
      - "docs/*"
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491
      with:
        go-version: '1.22'
    - name: Checkout code
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
    - name: Test
      run: go test -covermode atomic ./...
