name: coverage
on:
  push:
    branches: ['main']
    paths-ignore:
      - "docs/**"
      - "**.md"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**.md"
permissions: read-all
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - name: Install Go
      uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed
      with:
        go-version: 1.23
        cache: true
    - name: Check Coverage
      run: go test -covermode=atomic -coverprofile='coverage.cov' `go list ./... | grep -v -f .test_ignore.txt`
    - name: Coveralls Parallel
      uses: coverallsapp/github-action@4cdef0b2dbe0c9aa26bed48edb868db738625e79
      with:
        file: 'coverage.cov'
