name: docs
on:
  push:
    branches: ['main']
  pull_request:
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491
        with:
          go-version: '1.22'
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
      - run: ./.github/workflows/check-docs.sh
