name: docs
on:
  push:
    branches: ['main']
  pull_request:
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7
        with:
          go-version: '1.22'
          cache: true
      - run: ./.github/workflows/check-docs.sh
