name: get-started-tests
on:
  push:
    branches: ['main']
    paths-ignore:
      - "docs/*"
      - "!docs/testing/*"
      - "!docs/get-started.md"
  pull_request:
    paths-ignore:
      - "docs/*"
      - "!docs/testing/*"
      - "!docs/get-started.md"
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
    - name: Install Go
      uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7
      with:
        go-version: '1.22'
        cache: true
    - name: Install Python
      uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d
      with:
        python-version: '3.10'
    - name: Build gittuf
      run: make just-install
    - name: Test Getting Started
      run: python3 docs/testing/test-get-started-md.py
