name: Record change to non-main branch
on:
  push:
    branches-ignore:
      - 'main'
permissions: read-all
jobs:
  create-rsl-entry:
    if: github.repository == 'gittuf/gittuf'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Install gittuf
        uses: gittuf/gittuf-installer@a7644594c7def5a72ec719c2424825a5a8831548
      - name: Install gitsign
        uses: chainguard-dev/actions/setup-gitsign@main
      - name: Checkout repository
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
        with:
          fetch-depth: 0
      - name: Update RSL
        run: |
          git fetch origin refs/gittuf/reference-state-log:refs/gittuf/reference-state-log
          gittuf rsl record ${{ github.ref }}
          git push origin refs/gittuf/reference-state-log:refs/gittuf/reference-state-log
