name: Record change to non-main branch
on:
  push:
    branches-ignore:
      - 'main'
permissions: read-all
jobs:
  create-rsl-entry:
    if: github.repository == 'gittuf/gittuf'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Install gittuf
        uses: gittuf/gittuf-installer@fe644793aaaa419fef63800d5cf318663aa93105
      - name: Install gitsign
        uses: chainguard-dev/actions/setup-gitsign@main
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          fetch-depth: 0
      - name: Update RSL
        run: |
          git fetch origin refs/gittuf/reference-state-log:refs/gittuf/reference-state-log
          gittuf rsl record ${{ github.ref }}
          git push origin refs/gittuf/reference-state-log:refs/gittuf/reference-state-log
