name: gittuf Verification
on:
  workflow_run:
    workflows: ["Record change to main branch"]
    branches: [main]
    types:
      - completed
permissions: read-all
jobs:
  gittuf-verify:
    if: github.repository == 'gittuf/gittuf'
    runs-on: ubuntu-latest
    steps:
      - name: Install gittuf
        uses: gittuf/gittuf-installer@26235450ee63a0bb9d834ecd62b910783af72006
      - name: Checkout and verify repository
        run: |
          gittuf clone https://github.com/${{ github.repository }}
          cd gittuf
          gittuf verify-ref main --verbose
