name: golangci-lint
on:
  push:
    paths-ignore:
      - "docs/*"
  pull_request:
    paths-ignore:
      - "docs/*"
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe
        with:
          go-version: '1.21.x'
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: golangci-lint
        uses: golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc
        with:
          version: v1.54.2
          args: --timeout=5m
