name: Run demo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    

jobs:
  demo:
    name: Run demo 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout demo repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          repository: gittuf/demo

      - name: Install Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b
        with:
          python-version: '3.12'

      - name: Install gittuf-installer
        uses: gittuf/gittuf-installer@226868d1502eb509afafcf3c6722573785d6e013

      - name: Run demo script
        run: python run-demo.py --no-prompt
